version: "3.9"

services:
  pm2-example:
    container_name: pm2-example
    image: pm2-example:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ./back/api/.env
      - ./back/socket/.env
      - ./front/public/.env
      - ./front/admin/.env
    ports:
      - "80:80"     # Nginx reverse proxy (HTTP)
      - "443:443"   # Nginx reverse proxy (HTTPS, self-signed in dev)
    restart: unless-stopped
    # If you want live-reload while editing files on host, uncomment the volume below
    # and ensure your PM2 watch settings are as desired (backends already watch src/.env)
    # volumes:
    #   - ./:/app
