version: "3.9"

services:
  pm2-example:
    container_name: pm2-example
    image: pm2-example:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ./back/api/.env
      - ./back/socket/.env
      - ./front/public/.env
      - ./front/admin/.env
    ports:
      - "3000:3000"   # front/public (Next.js dev)
      - "5173:5173"   # front/admin (Vite dev)
      - "4000:4000"   # back/api (Express)
      - "5000:5000"   # back/socket (Socket.IO)
    restart: unless-stopped
    # If you want live-reload while editing files on host, uncomment the volume below
    # and ensure your PM2 watch settings are as desired (backends already watch src/.env)
    # volumes:
    #   - ./:/app
