# Це файл конфігурації Docker Compose для створення та управління контейнерами
# Docker Compose дозволяє описати всю архітектуру додатку в одному файлі

# Версія формату Docker Compose файлу
# Версія 3.8 підтримує більшість сучасних функцій Docker
version: '3.8'

# Секція services описує всі контейнери, які потрібно створити
# Кожний сервіс - це окремий контейнер з своїми налаштуваннями
services:
  
  # Назва нашого сервісу (можна вибрати будь-яку назву)
  # Ця назва буде використовуватись для звернення до контейнера
  redis-server:
    
    # Образ Docker, який буде використано для створення контейнера
    # redis:7-alpine - це офіційний образ Redis версії 7 на базі Alpine Linux
    # Alpine Linux - дуже легка операційна система, що робить образ меншим
    image: redis:7-alpine
    
    # Назва контейнера, яка буде відображатись в Docker Desktop
    # Якщо не вказати, Docker автоматично створить назву
    container_name: my-redis-container
    
    # Перезапуск контейнера у випадку його падіння або помилки
    # unless-stopped означає: завжди перезапускати, крім випадків коли ми самі зупинили
    restart: unless-stopped
    
    # Проброс портів з хост-машини в контейнер
    # Формат: "порт_на_хості:порт_в_контейнері"
    # 6379 - це стандартний порт для Redis
    ports:
      - "6379:6379"
    
    # Змінні оточення для налаштування Redis
    # Ці змінні будуть доступні всередині контейнера
    environment:
      # Встановлюємо пароль для підключення до Redis
      # УВАГА: в реальних проектах пароль слід зберігати в секретах!
      - REDIS_PASSWORD=mySecretPassword123
      
      # Налаштування логування Redis
      # notice - середній рівень деталізації логів
      - REDIS_LOG_LEVEL=notice
    
    # Команда, яка буде виконана при запуску контейнера
    # --requirepass встановлює пароль для Redis
    # --appendonly yes вмикає persistent зберігання даних
    command: redis-server --requirepass mySecretPassword123 --appendonly yes
    

