version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_dev
    container_name: dev-nginx-gateway
    ports:
      - "80:80"
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro