FROM nginx:1.29.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends mc \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 80


#
## Уберём дефолтный конфиг и добавим наш
#RUN rm -f /etc/nginx/conf.d/default.conf
#COPY nginx.conf /etc/nginx/nginx.conf
#
#EXPOSE 80
#
#CMD ["nginx", "-g", "daemon off;"]
