# ---------- 1) Build stage ----------
FROM node:22-alpine AS builder

WORKDIR /app

# Копируем только package* для более эффективного кеширования слоев
COPY ./src/package*.json ./

# Устанавливаем зависимости (для сборки нужны dev-зависимости)
RUN npm ci

# Копируем исходники и собираем production-бандл
COPY ./src ./
RUN npm run build


# ---------- 2) Runtime stage (nginx) ----------
FROM nginx:alpine AS runtime

COPY ./nginx.conf /etc/nginx/nginx.conf

# Копируем собранный бандл из build-этапа
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
