version: '3.9'

services:
  frontend:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile_dev
    environment:
      NEXT_PUBLIC_SSE_TIME_URL: ${NEXT_PUBLIC_SSE_TIME_URL:-http://localhost:5001/sse/time}
    ports:
      - "3000:3000"
    restart: unless-stopped  
    